/**
 * EDU GUARD AI — Mandatory Disclaimer Banner Component
 * Must be visible wherever an Early Support Indicator is displayed.
 */

import React from 'react';
import { ShieldCheck, Info } from 'lucide-react';

export default function DisclaimerBanner({ text, compact = false }) {
  const defaultText =
    text ||
    "This Early Support Indicator is generated by an AI system to assist faculty and mentors. It is NOT a judgment, ranking, or prediction of student failure. The indicator suggests that this student may benefit from a supportive check-in. All suggestions are optional. The final decision always rests with human review.";

  if (compact) {
    return (
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '8px',
          padding: '8px 12px',
          backgroundColor: 'rgba(79, 70, 229, 0.06)',
          border: '1px solid rgba(79, 70, 229, 0.15)',
          borderRadius: '8px',
          fontSize: '0.78rem',
          color: 'var(--text-secondary)',
          marginTop: '8px',
        }}
      >
        <Info size={16} color="var(--brand-primary)" style={{ flexShrink: 0 }} />
        <span>{defaultText}</span>
      </div>
    );
  }

  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'flex-start',
        gap: '12px',
        padding: '12px 16px',
        backgroundColor: 'rgba(79, 70, 229, 0.06)',
        border: '1px solid rgba(79, 70, 229, 0.18)',
        borderRadius: '12px',
        fontSize: '0.82rem',
        color: 'var(--text-secondary)',
        lineHeight: '1.45',
        margin: '12px 0',
      }}
    >
      <ShieldCheck
        size={20}
        color="var(--brand-primary)"
        style={{ flexShrink: 0, marginTop: '2px' }}
      />
      <div>
        <strong style={{ color: 'var(--text-main)', display: 'block', marginBottom: '2px' }}>
          Supportive AI Assistance Notice
        </strong>
        <span>{defaultText}</span>
      </div>
    </div>
  );
}
